/* Notes content for Unit 18: Advanced Arduino (CodeHS Unit 12). Rendered by ../notes-engine.js and ../notes-arduino.js */
(function () {
  var D = (window.NOTES_DATA = window.NOTES_DATA || {});
  function fileOf(k, name) { return "18-" + k + "-" + name + ".html"; }
  function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }
  function checklist(items, doneMsg) {
    return ["widget", { html: '<div class="rgrid" id="cl"></div><div class="fig" style="margin:12px 0 0"><svg viewBox="0 0 560 30" id="pb" role="img" aria-label="progress bar"></svg></div><div class="wout" id="cm"></div>', js: function (w) {
      var done = {}, box = w.querySelector("#cl");
      function up() { var n = Object.keys(done).filter(function (k) { return done[k]; }).length, f = n / items.length; w.querySelector("#pb").innerHTML = '<rect x="2" y="6" width="556" height="18" rx="9" fill="#10141C" stroke="#3A4658"/><rect x="2" y="6" width="' + (556 * f) + '" height="18" rx="9" fill="' + (f === 1 ? "#34D399" : "#5FD8DF") + '"/>'; w.querySelector("#cm").textContent = n + " of " + items.length + " ready" + (n === items.length ? ". " + doneMsg : ""); [].forEach.call(box.children, function (c, k) { c.classList.toggle("done", !!done[k]); }); }
      items.forEach(function (it, i) { var b = document.createElement("button"); b.className = "mi"; b.type = "button"; b.innerHTML = "<b>" + it[0] + "</b><br><span class='small'>" + it[1] + "</span>"; b.onclick = function () { done[i] = !done[i]; b.classList.toggle("done", !!done[i]); up(); }; box.appendChild(b); }); up(); } }];
  }

  D["18.1"] = {
    id: "18.1", title: "Arduino Challenges (Digital Watch & Elevator)", lessonFile: fileOf(1, "arduino-challenges-digital-watch-and-elevator"), codehs: "CodeHS 12.1", tags: ["Arduino", "LCD", "millis()"],
    deck: "Showing information on an LCD screen, counting time with millis() without freezing the program, and putting it all together in a digital watch and an elevator.",
    sections: [
      { h: "Show It on a Screen", f: "Section 1", story: "So far your Arduino could only talk through the Serial Monitor. An LCD screen lets a project show information on the project itself. A 16 by 2 LCD has two rows of 16 characters. You pick a position with setCursor(column, row) and write with print().",
        b: [["ard", "lcd", {}],
          ["code", "cpp", "#include <LiquidCrystal.h>\nLiquidCrystal lcd(12, 11, 5, 4, 3, 2);   // pins from the Tinkercad LCD\n\nvoid setup() {\n  lcd.begin(16, 2);          // 16 columns, 2 rows\n  lcd.print(\"Hello!\");\n}\n\nvoid loop() {\n  lcd.setCursor(0, 1);       // column 0, row 1 (the second row)\n  lcd.print(millis() / 1000);\n}"],
          ["cards", [["LCD screen", "A small display that shows characters in rows and columns."], ["lcd.setCursor(col, row)", "Moves the writing position. Rows and columns start at 0."], ["lcd.print()", "Writes text or numbers at the cursor."]]]] },
      { h: "Don't Freeze: millis()", f: "Section 2", story: "delay() stops everything. If the Arduino is asleep inside delay(1000), it can't notice a button press or update a screen. millis() returns how many milliseconds have passed since power on, so you can check the clock instead of sleeping. Compare the two below.",
        b: [["ard", "millis", {}],
          ["code", "cpp", "unsigned long lastTick = 0;\nint seconds = 0;\n\nvoid loop() {\n  if (millis() - lastTick >= 1000) {   // has a second passed?\n    lastTick = millis();               // remember when\n    seconds++;\n  }\n  // the rest of loop() keeps running all the time\n}"],
          ["predict", { lang: "cpp", code: "if (millis() - lastTick >= 500) {\n  lastTick = millis();\n  ledState = !ledState;\n}", q: "How often does the LED toggle?", opts: ["Every second", "Every half second", "Every 5 seconds", "Only once"], ans: 1, why: "The check passes every 500 ms, so the LED toggles twice a second. And loop() never paused." }],
          ["cards", [["millis()", "Milliseconds since the Arduino started. Use it to measure time without pausing."], ["Non-blocking code", "Code that keeps running while it waits, instead of sleeping in delay()."]]]] },
      { h: "Project: Digital Watch", f: "Challenge 1", story: "A watch is millis() turned into hours, minutes, and seconds. Divide to get the total seconds, then use % (the remainder) to wrap the digits. Slide the clock forward to see the math.",
        b: [["ard", "watch", {}], ["hint", "Because the watch uses millis() and not delay(), you can add a button that sets the time without the clock ever stopping."]] },
      { h: "Project: Elevator", f: "Challenge 2", story: "An elevator is a program that is always in one state: idle, moving up, moving down, or doors open. Buttons add floors to a queue, and each tick of the clock moves one step. Call a few floors and watch the state and the queue change.",
        b: [["ard", "elevator", {}],
          ["match", [["IDLE", "Waiting, nothing in the queue"], ["MOVING UP", "Target floor is above the current floor"], ["DOORS OPEN", "Arrived at a requested floor"], ["queue", "Floors still waiting to be visited"]]],
          ["hint", "Plan a project like this in pseudocode first: list the states, then what makes the program move from one state to the next."]] }
    ],
    quiz: [["What does lcd.setCursor(0, 1) do?", ["Clears the screen", "Moves to column 0 of the second row", "Prints 0 and 1", "Turns on the backlight"], 1, "Column 0, row 1."], ["Why is millis() better than delay() for a clock?", ["It is quieter", "It doesn't pause the rest of the program", "It is more accurate to the microsecond", "It uses less memory"], 1, "The program keeps running."], ["What does millis() return?", ["The time of day", "Milliseconds since the board started", "A random number", "Seconds since midnight"], 1, "Time since power on."], ["How do you get the seconds digit from total seconds?", ["total / 60", "total % 60", "total * 60", "total - 60"], 1, "The remainder after dividing by 60."]],
    end: ["Display it. Time it. Never block it.", "These three ideas turn a circuit into a real device."]
  };

  D["18.2"] = {
    id: "18.2", title: "Explore a New Sensor", lessonFile: fileOf(2, "explore-a-new-sensor"), codehs: "CodeHS 12.2", tags: ["Arduino", "Research", "Teaching"],
    deck: "How to research a sensor you have never used, work out how it connects and reads, and turn what you learned into a short lesson for classmates.",
    sections: [
      { h: "Research Like an Engineer", f: "Section 1", story: "Nobody knows every part. Engineers learn a new one by asking the same questions in the same order: what does it sense, how does it connect, what does its data look like, and how do I read it in code.",
        b: [["gfx", "flow", { steps: ["What does it sense?|light, motion, heat...", "How does it connect?|power, ground, signal", "What does it output?|analog or digital", "How do I read it?|analogRead or digitalRead", "Test it|print the values"], perRow: 5, colors: ["#5FD8DF", "#5FD8DF", "#FDD877", "#FDD877", "#34D399"] }, "Answer these five questions and you can use almost any sensor."],
          ["cards", [["Sensor", "A part that turns something in the world into a signal your Arduino can read."], ["Datasheet", "The manufacturer's document listing a part's pins, voltages, and behavior."], ["Analog vs. digital output", "Analog sensors give a range of values. Digital sensors give HIGH or LOW."]]]] },
      { h: "Sensor Chooser", f: "Try it", story: "Pick a sensor to see how it usually connects and reads. Use this as a model for your own research.",
        b: [["widget", { html: '<div class="chips2" id="sc"></div><div class="tblwrap"><table id="st"></table></div><div class="code" id="sk" style="margin-top:12px"></div>', js: function (w) {
          var S = [["Photoresistor", "How bright is it?", "Analog (A0)", "5V - sensor - A0 - resistor - GND", "int light = analogRead(A0);\nif (light < 300) {\n  digitalWrite(13, HIGH);   // dark: turn the lamp on\n}"], ["PIR motion sensor", "Is something moving?", "Digital (pin 2)", "5V, GND, signal to pin 2", "if (digitalRead(2) == HIGH) {\n  digitalWrite(13, HIGH);   // motion detected\n}"], ["Temperature sensor", "How warm is it?", "Analog (A0)", "5V, GND, output to A0", "float volts = analogRead(A0) * 5.0 / 1024;\nfloat tempC = (volts - 0.5) * 100;"], ["Tilt switch", "Is it tipped over?", "Digital (pin 3)", "One leg to pin 3, one to GND", "if (digitalRead(3) == LOW) {\n  tone(8, 440);   // tilted: sound the buzzer\n}"], ["Gas sensor", "Is there gas present?", "Analog (A1)", "5V, GND, output to A1", "if (analogRead(A1) > 400) {\n  digitalWrite(12, HIGH);   // alarm\n}"]], sel = 0, box = w.querySelector("#sc");
          function up() { var s = S[sel]; w.querySelector("#st").innerHTML = "<tr><th>Question</th><th>Answer</th></tr><tr><td>What does it sense?</td><td>" + s[1] + "</td></tr><tr><td>Output type</td><td>" + s[2] + "</td></tr><tr><td>Wiring</td><td>" + s[3] + "</td></tr>"; w.querySelector("#sk").innerHTML = esc(s[4]); [].forEach.call(box.children, function (c, k) { c.classList.toggle("on", k === sel); }); }
          S.forEach(function (s, i) { var b = document.createElement("button"); b.className = "chip"; b.type = "button"; b.textContent = s[0]; b.onclick = function () { sel = i; up(); }; box.appendChild(b); }); up(); } }],
          ["hint", "Part values vary by sensor and by Tinkercad component, so always check the part's details in the editor before you wire it."]] },
      { h: "Teach It", f: "Section 2", story: "Your job is to present the sensor to classmates. A good short lesson covers a few things in order. Click each item as you finish it.",
        b: [checklist([["Goal", "Say what the sensor does in one sentence."], ["Parts list", "List every part someone needs."], ["Wiring", "Show where every wire goes."], ["Code", "Walk through each line of the example."], ["Demo", "Run it so the class can see it work."], ["Check", "Ask one question to see if they understood."]], "You are ready to present.")] }
    ],
    quiz: [["What should you find out first about a new sensor?", ["Its price", "What it senses", "Its color", "Its weight"], 1, "Start with what it measures."], ["An analog sensor is read with...", ["digitalRead()", "analogRead()", "delay()", "print()"], 1, "analogRead gives a range."], ["What is a datasheet?", ["A spreadsheet", "A manufacturer's document describing a part", "A sensor", "A type of wire"], 1, "It lists the pins and behavior."], ["A good lesson ends with...", ["Nothing", "A question to check understanding", "A joke", "More wiring"], 1, "Checking for understanding."]],
    end: ["Learn it, then teach it.", "Explaining something is the fastest way to find out whether you really understand it."]
  };

  D["18.3"] = {
    id: "18.3", title: "Step-by-Step Arduino Project", lessonFile: fileOf(3, "step-by-step-arduino-project"), codehs: "CodeHS 12.3", tags: ["Arduino", "Instructions"],
    deck: "How to follow directions you did not write, how to tell when instructions are unclear, and how to rewrite them so a stranger can succeed.",
    sections: [
      { h: "Following Directions From a Stranger", f: "Section 1", story: "In this lesson you build a circuit using instructions written by someone you have never met. That is harder than it sounds, because the author knew things that they forgot to write down. As you build, notice every place you get stuck.",
        b: [["gfx", "flow", { steps: ["Read all steps first|before you build", "Build one step|then check it", "Note any confusion|write it down", "Test|does it work?", "Improve the directions|so the next person succeeds"], perRow: 5, colors: ["#8B9AAE", "#5FD8DF", "#FCA5A5", "#34D399", "#FDD877"] }, "The notes you take while building become your improvements later."],
          ["cards", [["Instructions", "Step-by-step directions for building or doing something."], ["Audience", "The people the directions are written for. What they already know changes what you must explain."], ["Revision", "Rewriting something to make it clearer."]]]] },
      { h: "Spot the Unclear Step", f: "Try it", story: "Each unclear instruction on the left has a clearer rewrite on the right. Pair them up. Notice what each rewrite adds: exact names, exact pins, and what to expect.",
        b: [["match", [["Connect the sensor to the board", "Connect the sensor's signal pin to Arduino pin 7"], ["Add the LED", "Place the LED's long leg in row 5 and its short leg in the ground rail"], ["Upload the code", "Click Code, paste the sketch, then click Start Simulation"], ["Make sure it works", "The LED should light when the button is pressed. If it doesn't, check the long leg"]]],
          ["predict", { q: "Which is the best rewrite of \"Plug in the resistor\"?", opts: ["Plug in the resistor somewhere", "Put a 220 ohm resistor between pin 9 and the LED's long leg", "Resistor goes by the LED", "Use a resistor"], ans: 1, why: "It names the part, its value, and exactly where it goes." }]] },
      { h: "Write Directions That Work", f: "Section 2", story: "Good instructions are specific, ordered, and testable. Use this checklist on your own directions before you give them to someone else.",
        b: [checklist([["Parts list first", "Everything needed up front."], ["One action per step", "Don't bundle three actions together."], ["Exact names and pins", "Say which pin, which row, which color."], ["Numbered in order", "The order is the plan."], ["A check after each step", "Tell the reader what they should see."], ["Picture or diagram", "Show it where words fall short."]], "Your directions are ready for a test reader.")] }
    ],
    quiz: [["Why can instructions you write be hard for others to follow?", ["Others are slow", "You know things you forgot to write down", "They are too long", "Pictures are not allowed"], 1, "The author's knowledge hides gaps."], ["Which step is clearer?", ["Wire it up", "Connect the red wire from 5V to the left power rail", "Do the wiring", "Make the connections"], 1, "It is specific."], ["What should you do before you start building?", ["Read all the steps", "Buy more parts", "Skip to the end", "Delete the code"], 0, "Read first."], ["A check after each step is useful because...", ["It slows you down", "You catch mistakes early", "It is required", "It adds pictures"], 1, "Errors don't pile up."]],
    end: ["Clear directions are a form of kindness.", "The best test is handing them to someone who has never seen the project."]
  };

  D["18.4"] = {
    id: "18.4", title: "Final Project", lessonFile: fileOf(4, "final-project"), codehs: "CodeHS 12.4", tags: ["Arduino", "Project"],
    deck: "How to choose a project, scope it to the time you have, build it in small working pieces, and present how it came together.",
    sections: [
      { h: "Scope It to Fit", f: "Section 1", story: "The most common reason a project fails is that it is too big for the time available. Scoping means cutting features until what is left can actually be finished. Set your time budget, then turn features on and off to see what fits.",
        b: [["widget", { html: '<div class="wrow"><label>days available <b id="dv"></b></label><input type="range" id="ds" min="2" max="12" value="6" style="max-width:240px"></div><div class="rgrid" id="fl" style="margin-top:10px"></div><div class="fig" style="margin:12px 0 0"><svg viewBox="0 0 560 34" id="bar" role="img" aria-label="time used compared to time available"></svg></div><div class="wout" id="fm"></div>', js: function (w) {
          var F = [["Blink an LED on a schedule", 0.5], ["Button controls the LED", 1], ["LCD shows status", 1.5], ["Servo opens a gate", 1.5], ["Ultrasonic distance alert", 2], ["Buzzer plays a tune", 1], ["Custom enclosure and wiring diagram", 2], ["WiFi dashboard", 5]], on = { 0: true, 1: true }, box = w.querySelector("#fl"), ds = w.querySelector("#ds");
          function up() { var total = 0, i, avail = +ds.value; for (i in on) if (on[i]) total += F[i][1]; w.querySelector("#dv").textContent = avail; var f = Math.min(1, total / avail); w.querySelector("#bar").innerHTML = '<rect x="2" y="6" width="556" height="22" rx="11" fill="#10141C" stroke="#3A4658"/><rect x="2" y="6" width="' + 556 * f + '" height="22" rx="11" fill="' + (total > avail ? "#EF4444" : "#34D399") + '"/>';
            w.querySelector("#fm").innerHTML = "Features chosen need <b>" + total + "</b> days of work. You have <b>" + avail + "</b>.<br>" + (total > avail ? "Too big. Cut a feature, and remember to leave time to test and fix." : total > avail * 0.8 ? "A tight fit. Leave a day of slack for surprises." : "This fits, with room to test."); [].forEach.call(box.children, function (c, k) { c.classList.toggle("done", !!on[k]); }); }
          F.forEach(function (f, i) { var b = document.createElement("button"); b.className = "mi"; b.type = "button"; b.innerHTML = "<b>" + f[0] + "</b><br><span class='small'>about " + f[1] + " day(s)</span>"; b.onclick = function () { on[i] = !on[i]; up(); }; box.appendChild(b); }); ds.oninput = up; up(); } }],
          ["cards", [["Scope", "How much a project includes. Scoping is deciding what to leave out."], ["Prototype", "A first rough working version that you improve in steps."]]]] },
      { h: "Build in Working Pieces", f: "Section 2", story: "Wire and test one part before you add the next. If something breaks, you know the last thing you added is the cause.",
        b: [["gfx", "flow", { steps: ["Idea|one sentence", "Plan|parts and pseudocode", "Build one piece|test it", "Add the next piece|test again", "Present|show and explain"], perRow: 5, colors: ["#8B9AAE", "#5FD8DF", "#FDD877", "#FDD877", "#34D399"] }, "Pieces two and three repeat for every feature."],
          ["order", { q: "Put the project steps in the best order.", lines: ["Write the idea in one sentence", "List the parts and write pseudocode", "Build and test the first feature", "Add the next feature and test again", "Prepare to present"], why: "Plan first, then grow the project one tested piece at a time.", hint: "Planning comes before building." }],
          ["predict", { q: "Your project has five features and two days left. What is the best move?", opts: ["Rush all five", "Cut features until the rest can be finished and tested", "Skip testing", "Start a new project"], ans: 1, why: "A smaller project that works beats a bigger one that doesn't." }]] },
      { h: "Present It", f: "Section 3", story: "A good presentation tells the story of how it came together, not just what it does. Click each item as you prepare it.",
        b: [checklist([["What it does", "Say it in one sentence, then demo it."], ["How it works", "Name the inputs and outputs."], ["What went wrong", "Share one bug and how you fixed it."], ["What you cut", "Explain one feature you left out and why."], ["What you learned", "Name something you could not have done at the start."], ["Questions", "Invite and answer questions."]], "You are ready to present.")] }
    ],
    quiz: [["What does scoping a project mean?", ["Making it bigger", "Deciding what to leave out so it can be finished", "Adding more parts", "Painting it"], 1, "Cutting features to fit the time."], ["Why build one piece at a time?", ["It is boring", "You know what caused any problem", "It saves wire", "The teacher likes it"], 1, "The last thing you added is the suspect."], ["What belongs in a presentation?", ["Only the demo", "What it does, how it works, and what you learned", "Only the code", "Nothing"], 1, "The story of the project."], ["What should you do first?", ["Build everything", "Write the idea in one sentence", "Present it", "Buy parts"], 1, "Start with the idea."]],
    end: ["Small, working, and finished.", "That beats big, broken, and unfinished every time."]
  };
})();
