[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/newsletter"
  to = "/.netlify/functions/newsletter"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/data"
  status = 200
