/* Notes content for Unit 17: Project: Guess the Word (CodeHS Unit 11). Rendered by ../notes-engine.js and ../minipy.js */
(function () {
  var D = (window.NOTES_DATA = window.NOTES_DATA || {});
  function fileOf(k, name) { return "17-" + k + "-" + name + ".html"; }
  function checklist(items, doneMsg) {
    return ["widget", { html: '<div class="rgrid" id="cl"></div><div class="fig" style="margin:12px 0 0"><svg viewBox="0 0 560 30" id="pb" role="img" aria-label="progress bar"></svg></div><div class="wout" id="cm"></div>', js: function (w) {
      var done = {}, box = w.querySelector("#cl");
      function up() { var n = Object.keys(done).filter(function (k) { return done[k]; }).length, f = n / items.length; w.querySelector("#pb").innerHTML = '<rect x="2" y="6" width="556" height="18" rx="9" fill="#10141C" stroke="#3A4658"/><rect x="2" y="6" width="' + (556 * f) + '" height="18" rx="9" fill="' + (f === 1 ? "#34D399" : "#5FD8DF") + '"/>'; w.querySelector("#cm").textContent = n + " of " + items.length + (n === items.length ? ". " + doneMsg : ""); [].forEach.call(box.children, function (c, k) { c.classList.toggle("done", !!done[k]); }); }
      items.forEach(function (it, i) { var b = document.createElement("button"); b.className = "mi"; b.type = "button"; b.innerHTML = "<b>" + it[0] + "</b><br><span class='small'>" + it[1] + "</span>"; b.onclick = function () { done[i] = !done[i]; up(); }; box.appendChild(b); }); up(); } }];
  }

  D["17.1"] = {
    id: "17.1", title: "Project: Guess the Word", lessonFile: fileOf(1, "project-guess-the-word"), codehs: "CodeHS 11.1", tags: ["Python", "Project"],
    deck: "How to plan and break down the Guess the Word game: what the finished game does, what state it has to remember, which tools from the course solve each part, and how to test it.",
    sections: [
      { h: "What the Finished Game Does", f: "Section 1", story: "You will use almost everything from this course to build a word-guessing game. Before writing any code, play a quick version below to see the behavior you are aiming for. Note what the game has to remember between guesses.",
        b: [["widget", { html: '<div class="fig" id="gw" style="margin:0 0 10px"></div><div class="wout" id="gm"></div><div class="chips2" id="gk" style="margin-top:8px"></div><div class="btns" style="justify-content:flex-start"><button class="btn" id="gn" type="button">New word</button></div>', js: function (w) {
          var words = ["python", "arduino", "circuit", "sensor", "loop", "string", "function"], secret, guessed, left;
          function newGame() { secret = words[Math.floor(Math.random() * words.length)]; guessed = []; left = 6; draw(); }
          function draw() { var mask = secret.split("").map(function (c) { return guessed.indexOf(c) >= 0 ? c.toUpperCase() : "_"; }), won = mask.indexOf("_") < 0, lost = left <= 0; var s = '<svg viewBox="0 0 560 90" role="img" aria-label="the word with blanks">'; mask.forEach(function (c, i) { var x = 10 + i * 56; s += '<rect x="' + x + '" y="10" width="48" height="56" rx="6" fill="#151A24" stroke="' + (c === "_" ? "#3A4658" : "#34D399") + '" stroke-width="2"/><text x="' + (x + 24) + '" y="48" font-size="28" fill="#EAEFF6" text-anchor="middle">' + (c === "_" ? "" : c) + "</text>"; }); s += "</svg>"; w.querySelector("#gw").innerHTML = s;
            w.querySelector("#gm").innerHTML = (won ? "<b style='color:#34D399'>You win!</b> " : lost ? "<b style='color:#FCA5A5'>Out of tries.</b> The word was <b>" + secret + "</b>. " : "") + "Wrong guesses left: <b>" + left + "</b> &nbsp; Guessed so far: <b>" + (guessed.join(" ") || "none") + "</b>";
            var box = w.querySelector("#gk"); box.innerHTML = ""; "abcdefghijklmnopqrstuvwxyz".split("").forEach(function (c) { var b = document.createElement("button"); b.className = "chip" + (guessed.indexOf(c) >= 0 ? " on" : ""); b.type = "button"; b.textContent = c; b.onclick = function () { if (won || lost || guessed.indexOf(c) >= 0) return; guessed.push(c); if (secret.indexOf(c) < 0) left--; draw(); }; box.appendChild(b); }); }
          w.querySelector("#gn").onclick = newGame; newGame(); } }],
          ["table", ["The game must remember", "Why"], [["The secret word", "To check every guess against it"], ["The letters guessed so far", "To show them and to catch repeats"], ["How many wrong guesses are left", "To know when the player loses"]]]] },
      { h: "Break It Into Pieces", f: "Section 2", story: "A project this size is too big to write in one go. Use top down design: start with the whole game, split it into jobs, and give each job a function. Then build and test one piece at a time.",
        b: [["gfx", "tree", { parent: ["play_game()", "the whole game"], children: [["choose a word", "pick the secret"], ["show progress", "blanks and letters"], ["get a guess", "ask the player"], ["check the guess", "right or wrong"], ["check for end", "win or lose"]] }, "Each box is a job small enough to write and test on its own."],
          ["gfx", "flow", { steps: ["Choose word|once at the start", "Show progress|every turn", "Get a guess|ask and validate", "Update state|right or wrong", "Done?|win, lose, or repeat"], perRow: 5, colors: ["#5FD8DF", "#5FD8DF", "#FDD877", "#FDD877", "#34D399"] }, "The game loop repeats the middle steps until the player wins or runs out of tries."]] },
      { h: "Match the Tool to the Job", f: "Section 3", story: "You already know the tools. The skill is recognizing which one fits. Pair each job in the game with the idea from the course that solves it.",
        b: [["match", [["Remember the letters guessed", "A list, with append()"], ["Is this letter in the word?", "The in keyword"], ["Show _ for unguessed letters", "A loop over the string with if/else"], ["Repeat until the game ends", "A while loop with a condition"], ["Pick a word to start", "A list of words"], ["Reject a letter already guessed", "An if with in"]]],
          ["hint", "Notice that nothing here is new. The project is the course, combined."],
          ["py", { code: "card = \"4539148803436467\"\nmasked = \"\"\nfor i in range(len(card)):\n    if i < len(card) - 4:\n        masked = masked + \"*\"\n    else:\n        masked = masked + card[i]\nprint(masked)", presets: [["Mask a card number", "card = \"4539148803436467\"\nmasked = \"\"\nfor i in range(len(card)):\n    if i < len(card) - 4:\n        masked = masked + \"*\"\n    else:\n        masked = masked + card[i]\nprint(masked)"], ["Track visited rooms", "visited = []\nroom = \"kitchen\"\nif room in visited:\n    print(\"been here\")\nelse:\n    visited.append(room)\n    print(\"new room\")\nprint(visited)"]], note: "These are the same patterns your game needs (build a string with a loop and an if, and remember things in a list), applied to different problems. Adapt the ideas to your own project." }]] },
      { h: "Test As You Go", f: "Section 4", story: "Test each piece before you add the next. When all of it works together, run through these cases. Click each one when you have tried it.",
        b: [checklist([["A correct guess", "The letter appears in every right spot."], ["A wrong guess", "Tries left goes down by one."], ["The same letter twice", "It is handled without penalty or a crash."], ["Uppercase and lowercase", "A and a count as the same guess."], ["Winning", "The game ends and says so."], ["Losing", "The game ends and shows the word."], ["Bad input", "Numbers, blanks, or two letters don't break it."]], "Your game is well tested.")] }
    ],
    quiz: [["What is the first thing to do on a big project?", ["Start typing code", "Break it into smaller jobs", "Add colors", "Test at the end"], 1, "Top down design."], ["Which structure remembers letters already guessed?", ["An int", "A list", "A float", "A comment"], 1, "A list you append to."], ["Which loop repeats until the game ends?", ["for with range", "while with a condition", "if", "def"], 1, "You don't know how many turns it will take."], ["Why test one piece at a time?", ["It is required", "You know where a bug is", "It is faster to type", "Tests are fun"], 1, "The newest piece is the suspect."]],
    end: ["The project is the course, put together.", "Plan the pieces, build one, test it, then add the next."]
  };

  D["17.2"] = {
    id: "17.2", title: "Intro to Computer Science in Python Completed", lessonFile: fileOf(2, "intro-to-computer-science-in-python-completed"), codehs: "CodeHS 11.2", tags: ["Python", "Wrap-up"],
    deck: "A look back at everything you can now do in Python, a skills checklist to find the gaps, and where to go next.",
    sections: [
      { h: "Look How Far You've Come", f: "Section 1", story: "You started by moving a turtle and ended by building a game from scratch. Each unit added a tool, and each tool made the next one possible.",
        b: [["gfx", "flow", { steps: ["Tracy|commands, loops, functions", "Basic Python|print, input, math", "Conditionals|decisions", "Loops|repetition", "Functions|reuse, errors", "Strings|text", "Data structures|lists, dicts", "Project|everything together"], perRow: 4, colors: ["#5FD8DF", "#5FD8DF", "#FDD877", "#FDD877", "#34D399", "#34D399", "#FCA5A5", "#FCA5A5"] }, "Eight steps from your first line of code to your own game."]] },
      { h: "What Can You Do?", f: "Check yourself", story: "Click every skill you could do right now without looking it up. The ones you leave blank show you what to review.",
        b: [checklist([["Print and take input", "print() and input() with conversion"], ["Do math and build strings", "Operators, f-strings, concatenation"], ["Make decisions", "if / elif / else with and, or, not"], ["Repeat things", "while and for loops, break, continue"], ["Write functions", "Parameters, return values, scope"], ["Handle errors", "try and except"], ["Work with strings", "Indexing, slicing, methods"], ["Use lists and tuples", "Loops, methods, 2D lists"], ["Use dictionaries", "Keys, values, get()"], ["Read someone else's code", "Trace it and predict the output"]], "You can do all of it. Time to build something new.")] },
      { h: "Where to Next?", f: "Section 2", story: "CodeHS offers more if you want it: classes and objects, harder turtle challenges, and practice for the Python certification. The best next step, though, is to build something you care about.",
        b: [["cards", [["Classes and objects", "Bundle data and functions into your own types, like a Dog or a Player."], ["Harder challenges", "More turtle problems that combine everything."], ["Certification practice", "Practice questions for the Python Level 1 certification."], ["Your own project", "A game, a tool, or a project that talks to an Arduino."]]],
          ["py", { code: "# Build something small of your own here.\nname = input(\"Name? \")\nprint(\"Hello,\", name)", inputs: "Ada", note: "This is a blank canvas. Try combining three ideas from the course." }]] }
    ],
    quiz: [["Which unit introduced decisions?", ["Strings", "Conditionals", "Functions", "Arduino"], 1, "if, elif, else."], ["What do you use to reuse code?", ["Functions", "Comments", "Variables only", "Print"], 0, "Define once, call often."], ["Which structure looks things up by key?", ["List", "Tuple", "Dictionary", "String"], 2, "A dictionary."], ["What best prepares you for harder problems?", ["Memorizing", "Building projects", "Avoiding errors", "Skipping tests"], 1, "Practice building."]],
    end: ["You can program.", "Everything from here is just bigger projects and sharper habits."]
  };
})();
