/* GENERATED by the lesson generator. Steps for 4.1-4.6 (8.x) and 5.1-5.6 (9.x): each assignment is a brand-new site, built top to bottom.
   What a lesson needs comes from the spiral-review policy in concepts.js (recent skills twice, older skills once, the basics always). */
(function (root) {
  var A = root.U7_ANSWERS = root.U7_ANSWERS || {};
  var D = {
 "8.1": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with its own **style.css** file, styled with **tag rules** and **classes**. Pick **one**: a robotics club, a pizza shop, or a gaming channel. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/external-css-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** nav",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 4: Two boxes side by side"
  },
  {
   "build": [
    "Add **two divs** next to each other. Give the first the **class** left and the second the **class** right. Put a **heading 2** and a **paragraph** inside each"
   ]
  },
  {
   "h": "Step 5: Two small tables"
  },
  {
   "build": [
    "Add **two tables**, each with a **header row** (3 columns in the first, 2 in the second) and **3 data rows**. Give both the **class** data"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.nav**: **text-align** center, **list-style-type** none, and a **hex** **background-color** (like #E8F0FF). **.nav li**: **display** inline and a **margin**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**",
    "**table**: a **solid border**, **text-align** center, **width** 90%, and a **margin**. **th**: **background-color**, **color** white, and **padding**. **td**: **padding**",
    "**.left**: **display** inline-block, **vertical-align** top, **width** 30%, a **background-color**, a **solid border**, and **padding**. **.right**: **display** inline-block, **vertical-align** top, **width** 60%, a **hex** **background-color**, a **dashed border**, and **padding**"
   ]
  },
  {
   "h": "Step 7: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "8.2": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that also styles single elements by **id**. Pick **one**: an animal shelter, a fitness gym, or a bookstore. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/css-id-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** nav",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight and the **id** welcome",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 4: Two boxes side by side"
  },
  {
   "build": [
    "Add **two divs** next to each other. Give the first the **class** left and the second the **class** right. Put a **heading 2** and a **paragraph** inside each"
   ]
  },
  {
   "h": "Step 5: Two small tables"
  },
  {
   "build": [
    "Add **two tables**, each with a **header row** (3 columns in the first, 2 in the second) and **3 data rows**. Give both the **class** data"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.nav**: **text-align** center, **list-style-type** none, and a **hex** **background-color** (like #E8F0FF). **.nav li**: **display** inline and a **margin**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**",
    "**table**: a **solid border**, **text-align** center, **width** 90%, and a **margin**. **th**: **background-color**, **color** white, and **padding**. **td**: **padding**",
    "**.left**: **display** inline-block, **vertical-align** top, **width** 30%, a **background-color**, a **solid border**, and **padding**. **.right**: **display** inline-block, **vertical-align** top, **width** 60%, a **hex** **background-color**, a **dashed border**, and **padding**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "(new today) **ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**. **#welcome**: a **solid border** and **padding**"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "8.3": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that shows **specificity**: a class rule beats a tag rule, one element can wear **two classes at once**, and **combined selectors** aim more precisely. Pick **one**: a bike shop, a band, or a science center. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/specificity-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** nav",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight and the **id** welcome",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)",
    "Add a second **paragraph** with **two classes** (note and tip)"
   ]
  },
  {
   "h": "Step 4: Two boxes side by side"
  },
  {
   "build": [
    "Add **two divs** next to each other. Give the first the **class** left and the second the **class** right. Put a **heading 2** and a **paragraph** inside each"
   ]
  },
  {
   "h": "Step 5: A small table"
  },
  {
   "build": [
    "Add a **table**, each with a **header row** (3 columns) and **3 data rows**. Give it the **class** data"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.nav**: **text-align** center, **list-style-type** none, and a **background-color**. **.nav li**: **display** inline and a **margin**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**",
    "**table**: a **solid border**, **text-align** center, **width** 90%, and a **margin**. **th**: **background-color**, **color** white, and **padding**. **td**: **padding**",
    "**.left**: **display** inline-block, **vertical-align** top, **width** 30%, a **background-color**, a **solid border**, and **padding**. **.right**: **display** inline-block, **vertical-align** top, **width** 60%, a **background-color**, a **dashed border**, and **padding**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**. **#welcome**: a **solid border** and **padding**",
    "(new today) **classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**. Write a **combined** rule **p.tip** (a tag stuck to a class) with a **background-color**",
    "(new today) **combined selectors:** **p.tip** above, and **ul li** (one tag inside another): a **margin**"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "8.4": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with smooth **hover effects** that use **transitions**. Pick **one**: a robotics club, a fitness gym, or a band. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/hover-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** nav",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight and the **id** welcome",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)",
    "Add a second **paragraph** with **two classes** (note and tip)"
   ]
  },
  {
   "h": "Step 4: Two boxes side by side"
  },
  {
   "build": [
    "Add **two divs** next to each other. Give the first the **class** left and the second the **class** right. Put a **heading 2** and a **paragraph** inside each"
   ]
  },
  {
   "h": "Step 5: A small table"
  },
  {
   "build": [
    "Add a **table**, each with a **header row** (3 columns) and **3 data rows**. Give it the **class** data"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.nav**: **text-align** center, **list-style-type** none, and a **background-color**. **.nav li**: **display** inline and a **margin**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**",
    "**table**: a **solid border**, **text-align** center, **width** 90%, and a **margin**. **th**: **background-color**, **color** white, and **padding**. **td**: **padding**",
    "**.left**: **display** inline-block, **vertical-align** top, **width** 30%, a **background-color**, a **solid border**, and **padding**. **.right**: **display** inline-block, **vertical-align** top, **width** 60%, a **background-color**, a **dashed border**, and **padding**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**. **#welcome**: a **solid border** and **padding**",
    "**classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**. Write a **combined** rule **p.tip** (a tag stuck to a class) with a **background-color**",
    "**combined selectors:** **p.tip** above, and **ul li** (one tag inside another): a **margin**",
    "(new today) **hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**. Do the same for **td**: a **transition** in the normal **td** rule and **td:hover** to change the **background-color**"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "8.5": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that uses **flexbox** for two sections. Pick **one**: a pizza shop, a bookstore, or a science center. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/flexbox-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** menu",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)",
    "Add a second **paragraph** with **two classes** (note and tip)"
   ]
  },
  {
   "h": "Step 4: A row of facts"
  },
  {
   "build": [
    "Add a **div** with the **class** stats that holds **3 short paragraphs** (like facts)"
   ]
  },
  {
   "h": "Step 5: A small table"
  },
  {
   "build": [
    "Add a **table**, each with a **header row** (3 columns) and **3 data rows**. Give it the **class** data"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.menu**: **display** flex, **justify-content** (try space-around), **align-items** center, **list-style-type** none, and a **background-color**. **.menu li**: **font-weight** bold",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**",
    "**table**: a **solid border**, **text-align** center, **width** 90%, and a **margin**. **th**: **background-color**, **color** white, and **padding**. **td**: **padding**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**",
    "**classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**. Write a **combined** rule **p.tip** (a tag stuck to a class) with a **background-color**",
    "**combined selectors:** **p.tip** above, and **ul li** (one tag inside another): a **margin**",
    "**hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**. Do the same for **td**: a **transition** in the normal **td** rule and **td:hover** to change the **background-color**",
    "(new today) **flexbox:** **.menu** (above) uses **display** flex with **justify-content** and **align-items**. **.stats**: **display** flex, **justify-content** (try space-between), **align-items** center, a **background-color**, a **solid border**, and **padding**"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "8.6": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that uses **grid** for two sections. Pick **one**: a gaming channel, an animal shelter, or a bike shop. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "Stuck? Read the notes: schscomputerscience.com/ist/unit-8/grid-notes.html"
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Click the **style.css** tab (all your styling goes there, not in the page)",
    "In the head, add a **link** to your CSS file, which is named **style.css**"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** menu",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)"
   ]
  },
  {
   "h": "Step 4: A row of facts"
  },
  {
   "build": [
    "Add a **div** with the **class** stats that holds **3 short paragraphs** (like facts)"
   ]
  },
  {
   "h": "Step 5: A gallery and a facts grid"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**",
    "Add a **div** with the **class** facts that holds **4 short paragraphs**"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.menu**: **display** flex, **justify-content** (try space-around), **align-items** center, **list-style-type** none, and a **background-color**. **.menu li**: **font-weight** bold",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**",
    "**classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**",
    "**combined selectors:** **ul li** (one tag inside another): a **margin**",
    "**hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**. Do the same for **.bullets li**: a **transition** in the normal rule and **.bullets li:hover** to change the **background-color**",
    "**flexbox:** **.menu** (above) uses **display** flex with **justify-content** and **align-items**. **.stats**: **display** flex, **justify-content** (try space-between), **align-items** center, a **background-color**, a **solid border**, and **padding**",
    "(new today) **grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**. **.facts**: **display** grid, **grid-template-columns** with 2 equal columns, and a **gap**. **.facts p**: a **background-color**, **padding**, and **text-align** center"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.1": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that loads **Bootstrap**, a giant ready-made stylesheet, and still uses the skills from the CSS unit. Pick **one**: an animal shelter, a band, or a robotics club. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name and give it an **id** named banner",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** menu",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)"
   ]
  },
  {
   "h": "Step 4: A row of facts"
  },
  {
   "build": [
    "Add a **div** with the **class** stats that holds **3 short paragraphs** (like facts)"
   ]
  },
  {
   "h": "Step 5: A gallery and a facts grid"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**",
    "Add a **div** with the **class** facts that holds **4 short paragraphs**"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.menu**: **display** flex, **justify-content** (try space-around), **align-items** center, **list-style-type** none, and a **background-color**. **.menu li**: **font-weight** bold",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**ids:** an id rule starts with a **#** before the name. **#banner**: a **margin** and **padding**",
    "**classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**",
    "**combined selectors:** **ul li** (one tag inside another): a **margin**",
    "**hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**",
    "**flexbox:** **.menu** (above) uses **display** flex with **justify-content** and **align-items**. **.stats**: **display** flex, **justify-content** (try space-between), **align-items** center, a **background-color**, a **solid border**, and **padding**",
    "**grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**. **.facts**: **display** grid, **grid-template-columns** with 2 equal columns, and a **gap**. **.facts p**: a **background-color**, **padding**, and **text-align** center"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.2": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website that uses Bootstrap's **grid**: a container, rows, and columns. Pick **one**: a fitness gym, a science center, or a pizza shop. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** menu",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked",
    "Add a **paragraph** with **two classes** at once (note and framed, separated by a space)"
   ]
  },
  {
   "h": "Step 4: A gallery and a facts grid"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**",
    "Add a **div** with the **class** facts that holds **4 short paragraphs**"
   ]
  },
  {
   "h": "Step 5: Bootstrap sections"
  },
  {
   "build": [
    "Add a **div** with Bootstrap's **container** class. **Inside it**, add a **div** with the **row** class, and **inside the row** add **2 divs** with the **col** class. Put a **heading 2** and a **paragraph** in each column"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.menu**: **display** flex, **justify-content** (try space-around), **align-items** center, **list-style-type** none, and a **background-color**. **.menu li**: **font-weight** bold",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**classes together:** **.note**: a **different color** from your p rule and **text-align** center (a class beats a tag rule). **.framed**: a **solid border** and **padding**",
    "**combined selectors:** **ul li** (one tag inside another): a **margin**",
    "**hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**",
    "**flexbox:** **.menu** (above) uses **display** flex with **justify-content** and **align-items**",
    "**grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**. **.facts**: **display** grid, **grid-template-columns** with 2 equal columns, and a **gap**. **.facts p**: a **background-color**, **padding**, and **text-align** center"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.3": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with Bootstrap **utility classes** and **buttons**. Pick **one**: a bookstore, a bike shop, or a gaming channel. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: Banner, menu, and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Under it, add a **bullet list** with **3 list items**, each with a **link** (https://) that opens in the same tab. Give the list the **class** menu",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 3: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 4: A gallery"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**"
   ]
  },
  {
   "h": "Step 5: Bootstrap sections"
  },
  {
   "build": [
    "Add a **div** with Bootstrap's **container** class. **Inside it**, add **2 divs** with the **row** class, and **inside each row** add **2 divs** with the **col** class. Put a **heading 2** and a **paragraph** in each column",
    "Add Bootstrap classes: a **text color** class (like **text-primary**) on a heading, a **background** class (like **bg-light**) on a paragraph, and a **bold** class (like **fw-bold**) on a heading. In a column, add a **link** (https://) with Bootstrap's **btn** class plus a style class (like **btn-primary**)"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "A class rule starts with a **dot** before the name. **.menu**: **display** flex, **justify-content** (try space-around), **align-items** center, **list-style-type** none, and a **background-color**. **.menu li**: **font-weight** bold",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 7: More rules in style.css"
  },
  {
   "build": [
    "**hover:** in the **a** rule add a **transition** (like all 0.3s), then write **a:hover** (a tag, a colon, the word hover) to change **color** and **background-color**",
    "**flexbox:** **.menu** (above) uses **display** flex with **justify-content** and **align-items**",
    "**grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**"
   ]
  },
  {
   "h": "Step 8: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.4": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with a Bootstrap **navbar** across the top. Pick **one**: a robotics club, a bookstore, or a band. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: The Bootstrap navbar (new today)"
  },
  {
   "build": [
    "At the **very top of the body**, add a **nav** tag with Bootstrap's **navbar** class, plus **navbar-expand**, **bg-dark**, and **navbar-dark**",
    "**Inside the nav**, add a **link** with the **navbar-brand** class showing your site's name, then a **div** with the **navbar-nav** class that holds **3 links** with the **nav-link** class (like Home, About, Contact), each with a full https:// address"
   ]
  },
  {
   "h": "Step 3: Heading and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 4: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 5: A row of facts"
  },
  {
   "build": [
    "Add a **div** with the **class** stats that holds **3 short paragraphs** (like facts)"
   ]
  },
  {
   "h": "Step 6: A gallery"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**"
   ]
  },
  {
   "h": "Step 7: Bootstrap sections"
  },
  {
   "build": [
    "Add a **div** with Bootstrap's **container** class. **Inside it**, add **2 divs** with the **row** class, and **inside each row** add **2 divs** with the **col** class. Put a **heading 2** and a **paragraph** in each column",
    "Add Bootstrap classes: a **text color** class (like **text-primary**) on **2 headings**, a **background** class (like **bg-light**) on a paragraph, and a **bold** class (like **fw-bold**) on a heading. In **2 different columns**, add a **link** (https://) with Bootstrap's **btn** class plus a style class (like **btn-primary**)"
   ]
  },
  {
   "h": "Step 8: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 9: More rules in style.css"
  },
  {
   "build": [
    "**flexbox:** **.stats**: **display** flex, **justify-content** (try space-between), **align-items** center, a **background-color**, a **solid border**, and **padding**",
    "**grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**"
   ]
  },
  {
   "h": "Step 10: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.5": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with a row of Bootstrap **cards**. Pick **one**: a pizza shop, an animal shelter, or a science center. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: The Bootstrap navbar (new today)"
  },
  {
   "build": [
    "At the **very top of the body**, add a **nav** tag with Bootstrap's **navbar** class, plus **navbar-expand**, **bg-dark**, and **navbar-dark**",
    "**Inside the nav**, add a **link** with the **navbar-brand** class showing your site's name, then a **div** with the **navbar-nav** class that holds **3 links** with the **nav-link** class (like Home, About, Contact), each with a full https:// address"
   ]
  },
  {
   "h": "Step 3: Heading and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 4: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 5: A gallery"
  },
  {
   "build": [
    "Add a **div** with the **class** gallery. Inside it, add **3 linked pictures** (each with a real **alt**) and give each **picture** the **class** thumb. Make one link open in a **new tab**"
   ]
  },
  {
   "h": "Step 6: Bootstrap sections"
  },
  {
   "build": [
    "Add a **div** with Bootstrap's **container** class. **Inside it**, add a **div** with the **row** class, and **inside the row** add **2 divs** with the **col** class. Put a **heading 2** and a **paragraph** in each column",
    "Add Bootstrap classes: a **text color** class (like **text-primary**) on a heading, a **background** class (like **bg-light**) on a paragraph, and a **bold** class (like **fw-bold**) on a heading. In a column, add a **link** (https://) with Bootstrap's **btn** class plus a style class (like **btn-primary**)",
    "Inside the container, add another **row** with **3 columns**. In each column, add a **div** with the **card** class. Inside each card: a linked **image** with the **card-img-top** class, then a **div** with the **card-body** class that holds a **heading** (**card-title**), a **paragraph** (**card-text**), and a **link** (**btn** plus **btn-primary**)"
   ]
  },
  {
   "h": "Step 7: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 8: More rules in style.css"
  },
  {
   "build": [
    "**grid:** **.gallery**: **display** grid, **grid-template-columns** with 3 equal columns (like 1fr 1fr 1fr), and a **gap**. **.thumb**: **width** 100% and a **solid border**"
   ]
  },
  {
   "h": "Step 9: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ],
 "9.6": [
  {
   "h": "What you are building"
  },
  {
   "p": "A brand-new website with a Bootstrap **form**. Pick **one**: a gaming channel, a fitness gym, or a bike shop. Click **Checks** any time to see your score. The **Concepts** tab lists every tag and style this page needs."
  },
  {
   "p": "**Every theme uses these same steps.** Use **named colors** (like navy or tomato) unless a step says hex. Dark backgrounds need light text. Each step says the least you must add: you can ALWAYS add more."
  },
  {
   "h": "Step 1: Start a brand-new site"
  },
  {
   "build": [
    "This is a **new website**. Open the **index.html** tab and type the **doctype**, **html**, **head**, and **body**. In the head, add a **title** with your site's name",
    "Go to **getbootstrap.com**, open **Getting Started**, and copy the official **CSS link** (a full https:// address). Add it **inside the head**",
    "In the head, add a **link** to your CSS file, which is named **style.css**, **under** the Bootstrap link so your styles win"
   ]
  },
  {
   "h": "Step 2: The Bootstrap navbar (new today)"
  },
  {
   "build": [
    "At the **very top of the body**, add a **nav** tag with Bootstrap's **navbar** class, plus **navbar-expand**, **bg-dark**, and **navbar-dark**",
    "**Inside the nav**, add a **link** with the **navbar-brand** class showing your site's name, then a **div** with the **navbar-nav** class that holds **3 links** with the **nav-link** class (like Home, About, Contact), each with a full https:// address"
   ]
  },
  {
   "h": "Step 3: Heading and picture"
  },
  {
   "build": [
    "Add **one heading 1** with your site's name",
    "Add a **paragraph**. Click inside it, then click **Insert** on your first picture (Checks, then My images). The editor writes the picture wrapped in a link for you. Change that link to a **real website** (a full address starting with https://) and change the **alt** to a real description. Give the **picture** the **class** hero and make its link open in a **new tab**"
   ]
  },
  {
   "h": "Step 4: Intro and lists"
  },
  {
   "build": [
    "Add a **heading 2** and a **paragraph** with the **class** highlight",
    "Add a **bullet list** of **3 items** with the **class** bullets, then a **numbered list** of **3 items** (a name, a dash, and a short description) with the **class** ranked"
   ]
  },
  {
   "h": "Step 5: Bootstrap sections"
  },
  {
   "build": [
    "Add a **div** with Bootstrap's **container** class. **Inside it**, add a **div** with the **row** class, and **inside the row** add **2 divs** with the **col** class. Put a **heading 2** and a **paragraph** in each column",
    "Add Bootstrap classes: a **text color** class (like **text-primary**) on a heading, a **background** class (like **bg-light**) on a paragraph, and a **bold** class (like **fw-bold**) on a heading. In a column, add a **link** (https://) with Bootstrap's **btn** class plus a style class (like **btn-primary**)",
    "Inside the container, add another **row** with **3 columns**. In each column, add a **div** with the **card** class. Inside each card: a linked **image** with the **card-img-top** class, then a **div** with the **card-body** class that holds a **heading** (**card-title**), a **paragraph** (**card-text**), and a **link** (**btn** plus **btn-primary**)",
    "At the bottom of the container, add a **form** with a heading, then **2 labels** (**form-label**) each followed by an **input** (**form-control**), then a **button** with type submit and the classes **btn btn-success**"
   ]
  },
  {
   "h": "Step 6: Style the page in style.css"
  },
  {
   "build": [
    "Click the **style.css** tab. In a CSS file there are **no style tags**, **no quotes** around values, and every rule is a selector, curly braces, and **property: value;** lines",
    "**body**: **background-color** (a light named color), **font-family** sans-serif, and **margin** (like 0 20px)",
    "**h1**: **color** white, **background-color**, **font-size** 38px, **text-align** center, and a **solid border**. **h2**: **color** and **font-size** 26px. **p**: **margin** and **color**. **a**: **color**",
    "**.hero**: **width** 320px, a **solid border**, and a **margin**. **.highlight**: **background-color** and **padding**. **.bullets**: **background-color**"
   ]
  },
  {
   "h": "Step 7: Test and submit"
  },
  {
   "build": [
    "Click **Checks**. Fix every red line. The **Use what you already know** list has to turn green too: for each red item, add the missing use where it fits the page",
    "Choose your class period at the top, then click **Submit** (you can submit again to replace it)"
   ]
  }
 ]
};
  Object.keys(D).forEach(function (k) { A[k] = D[k]; });
})(typeof window !== "undefined" ? window : globalThis);
