/* Notes content for Unit 19: Final Exam (CodeHS Unit 13). Rendered by ../notes-engine.js and ../minipy.js */
(function () {
  var D = (window.NOTES_DATA = window.NOTES_DATA || {});
  function fileOf(k, name) { return "19-" + k + "-" + name + ".html"; }
  function checklist(items, doneMsg) {
    return ["widget", { html: '<div class="rgrid" id="cl"></div><div class="fig" style="margin:12px 0 0"><svg viewBox="0 0 560 30" id="pb" role="img" aria-label="progress bar"></svg></div><div class="wout" id="cm"></div>', js: function (w) {
      var done = {}, box = w.querySelector("#cl");
      function up() { var n = Object.keys(done).filter(function (k) { return done[k]; }).length, f = n / items.length; w.querySelector("#pb").innerHTML = '<rect x="2" y="6" width="556" height="18" rx="9" fill="#10141C" stroke="#3A4658"/><rect x="2" y="6" width="' + (556 * f) + '" height="18" rx="9" fill="' + (f === 1 ? "#34D399" : "#5FD8DF") + '"/>'; w.querySelector("#cm").textContent = n + " of " + items.length + " ready" + (n === items.length ? ". " + doneMsg : ". Review the ones you left blank."); [].forEach.call(box.children, function (c, k) { c.classList.toggle("done", !!done[k]); }); }
      items.forEach(function (it, i) { var b = document.createElement("button"); b.className = "mi"; b.type = "button"; b.innerHTML = "<b>" + it[0] + "</b><br><span class='small'>" + it[1] + "</span>"; b.onclick = function () { done[i] = !done[i]; up(); }; box.appendChild(b); }); up(); } }];
  }

  D["19.1"] = {
    id: "19.1", title: "Final Exam", lessonFile: fileOf(1, "final-exam"), codehs: "CodeHS 13.1", tags: ["Python", "Review"],
    deck: "A study guide for the final exam: the big idea from each unit, practice at reading and fixing code, and a readiness checklist so you know what to review.",
    sections: [
      { h: "The Course in One Map", f: "Study map", story: "The exam covers your knowledge of coding in Python. Every unit added one idea, and each new idea used the ones before it. Click through the cards and say each answer out loud before you flip it.",
        b: [["gfx", "flow", { steps: ["Turtle|commands, loops", "Basics|print, input, types", "Conditionals|if, and/or/not", "Loops|while, for, range", "Functions|def, return, scope", "Strings|index, slice, methods", "Structures|list, tuple, dict", "Project|put it together"], perRow: 4 }, "Eight areas, each one building on the last."],
          ["cards", [["print() and input()", "print shows. input returns a string, so convert with int() or float()."], ["Types and operators", "int, float, str, bool. // and % for division and remainder. + joins strings."], ["if / elif / else", "The first True condition runs. Combine with and, or, not. == compares, = stores."], ["while and for", "while repeats on a condition. for walks a sequence. range() stops before its end."], ["Functions", "def, parameters, return. Locals stay inside. print shows, return hands back."], ["try / except", "Catch an exception so the program continues."], ["Strings", "Indexed from 0, sliced with [start:stop:step], immutable. Methods return new strings."], ["Lists and tuples", "Lists change, tuples don't. append, pop, sort, 2D lists, comprehensions."], ["Dictionaries", "Key: value pairs. d[key], d.get(key), key in d."], ["== vs is", "Equal contents versus the same object. Copy a list with .copy()."]]]] },
      { h: "Read the Code", f: "Practice", story: "Reading code is half the exam. Predict each result in your head before you click.",
        b: [["predict", { code: "x = 17\nprint(x // 5, x % 5)", q: "What prints?", opts: ["3 2", "3.4 2", "3 3", "2 3"], ans: 0, why: "17 // 5 is 3 and 17 % 5 is 2." }],
          ["predict", { code: "total = 0\nfor i in range(1, 5):\n    if i % 2 == 0:\n        total += i\nprint(total)", q: "What prints?", opts: ["6", "10", "4", "2"], ans: 0, why: "Only the even values 2 and 4 are added: 2 + 4 = 6." }],
          ["predict", { code: "word = \"program\"\nprint(word[1:4], word[-1])", q: "What prints?", opts: ["rog m", "rogr m", "rog r", "ro m"], ans: 0, why: "word[1:4] is rog and word[-1] is m." }],
          ["predict", { code: "def f(a, b=2):\n    return a * b\n\nprint(f(3), f(3, 4))", q: "What prints?", opts: ["6 12", "5 7", "3 4", "6 7"], ans: 0, why: "f(3) uses the default b = 2, so 6. f(3, 4) is 12." }],
          ["predict", { code: "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(len(a))", q: "What prints?", opts: ["3", "4", "1", "Error"], ans: 1, why: "a and b are the same list, so the append shows up in both." }],
          ["predict", { code: "d = {\"x\": 1, \"y\": 2}\nprint(d.get(\"z\", 0) + d[\"y\"])", q: "What prints?", opts: ["2", "3", "0", "KeyError"], ans: 0, why: "get returns the default 0 for a missing key, and d[\"y\"] is 2." }]] },
      { h: "Fix the Code", f: "Practice", story: "Each program has a bug. Run it, read the error, then edit the code to fix it and run again.",
        b: [["py", { code: "scores = [90, 75, 82]\ntotal = 0\nfor s in scores:\ntotal = total + s\nprint(total)", presets: [["Missing indent", "scores = [90, 75, 82]\ntotal = 0\nfor s in scores:\ntotal = total + s\nprint(total)"], ["Type mismatch", "age = 15\nprint(\"Next year you will be \" + age + 1)"], ["Off by one", "for i in range(1, 5):\n    print(i)\nprint(\"I wanted 1 through 5\")"], ["Wrong index", "word = \"hello\"\nprint(word[5])"], ["= vs ==", "x = 5\nif x = 5:\n    print(\"five\")"], ["Scope", "def add_one():\n    total = 1\n\nadd_one()\nprint(total)"], ["Immutable", "t = (1, 2, 3)\nt[0] = 9"]], note: "Every preset is broken on purpose. Change it until it works." }]] },
      { h: "Am I Ready?", f: "Readiness", story: "Click the topics you could explain to a friend without notes. Review whatever stays blank.",
        b: [checklist([["Types and conversion", "int(), float(), str(), input()"], ["Math and string operators", "// % ** and + *"], ["Conditions", "if, elif, else, and, or, not"], ["Loops", "while, for, range, break, continue"], ["Functions", "Parameters, return, scope, defaults"], ["Exceptions", "try and except"], ["Strings", "Indexing, slicing, methods"], ["Lists and tuples", "Methods, loops, 2D lists"], ["Dictionaries", "Keys, values, get()"], ["Equality and identity", "== versus is"]], "You are ready for the exam.")] },
      { h: "Match the Pairs", f: "Practice", story: "A last quick check. Pair each term with its meaning.",
        b: [["match", [["//", "Integer division"], ["%", "Remainder"], ["not in", "True if text is absent"], ["return", "Hand a value back"], ["immutable", "Can't be changed in place"], ["{ }", "Dictionary"], ["[x for x in y]", "List comprehension"], ["a, b = b, a", "Swap two variables"]]]] }
    ],
    quiz: [["What does input() return?", ["An int", "A string", "A float", "A bool"], 1, "Always a string."], ["What is the value of range(2, 6) as a list?", ["[2, 3, 4, 5, 6]", "[2, 3, 4, 5]", "[3, 4, 5, 6]", "[2, 6]"], 1, "The stop value is not included."], ["Which is correct for the last item of a list named items?", ["items[len(items)]", "items[-1]", "items[last]", "items.end"], 1, "-1."], ["What does a function without a return statement give back?", ["0", "None", "An error", "An empty string"], 1, "None."], ["Which loop is best when you don't know how many times to repeat?", ["for with range", "while", "if", "def"], 1, "A condition decides."], ["What does \"Hello\"[1:3] give?", ["He", "el", "ell", "Hel"], 1, "Indexes 1 and 2."], ["Which exception does int(\"abc\") raise?", ["TypeError", "ValueError", "NameError", "IndexError"], 1, "ValueError."], ["After b = a for a list, what is a is b?", ["True", "False", "None", "Error"], 0, "Same object."]],
    end: ["Read it. Trace it. Fix it.", "If you can do those three with Python code, you are ready."]
  };
})();
